### PR TITLE
Numeric timestamp option

### PR DESCRIPTION
**Pull request by mcfearsome**

### CODE REVIEW

**Comment by mr-smithers-excellent** [comment]
Hi @mcfearsome, thanks for the PR. Can you please provide some context around your feature request?

**Comment by mcfearsome** [comment]
> Hi @mcfearsome, thanks for the PR. Can you please provide some context around your feature request?

Well it seems I was trying to work around some poor documentation at https://fluxcd.io/docs/components/image/imagepolicies/#examples but this is also how I have tagged in the past as I don't need anything human readable. I was going to add direct control over the format but figured it best to leave it be to help retain sort-ability.

**Comment by mr-smithers-excellent** [comment]
@mcfearsome - the default timestamps here are already compliant with Flux v2's sorting mechanism. Is there a reason you want non-human-readable aside from the fact that's what you're used to?

**Comment by mcfearsome** [comment]
Yeah I got there eventually and no, not really. Just my own internal eccentricities that make me prefer it the other way.

**Comment by mr-smithers-excellent** [comment]
In that case, are you still interested in merging the feature? Looks like I need to do a bit of housekeeping with the test permissions, which I'm happy to do.

**Pull request closed without merging**
