### PR TITLE
Adds support for multi-platform builds

### PR DESCRIPTION
**Pull request by mr-smithers-excellent**
- Adds support for multi-platform builds with `multiPlatform` input
- Sets up default `docker-container` driver
- Allows for overriding default Docker driver with input `overrideDriver`

### CODE REVIEW

**Comment by mr-smithers-excellent** [comment]
Fixes #107

**Comment by mr-smithers-excellent** [comment]
@gavinastur - could you give this branch a try and see if meets your teams' needs? Updated documentation on multi-platform builds can be found [here](https://github.com/mr-smithers-excellent/docker-build-push/tree/buildx#multi-platform-builds)

Quick example (no need to set up buildx in preceding step unless customization is required)
```
- uses: mr-smithers-excellent/docker-build-push@buildx
    name: Build & push Docker image
    with:
      image: repo/image
      registry: docker.io
      multiPlatform: true
      platform: linux/amd64,linux/arm64,linux/arm/v7
```

**Comment by gavinastur** [comment]
@mr-smithers-excellent Nice! Will give this a try this afternoon.

**Comment by gavinastur** [comment]
@mr-smithers-excellent we've integrated our side and all looks good with various combinations 👍, i see you also added dependabot config 🥇

**Comment by mr-smithers-excellent** [comment]
@gavinastur - great news! I'll get this released in a v6 release today.

**Comment by mr-smithers-excellent** [comment]
@gavinastur many apologies! It was not my intention to discredit your great work. If you'd like an easy feature so that you can be listed, I'd be happy to have you handle #121

**Comment by gavinastur** [comment]
@mr-smithers-excellent thanks! Yes let me take a look, should have some time this week to put this together.

**Pull request merged**
