### PR TITLE
fix: update @actions/core to 1.10.0

### LINKED ISSUE #112: Set output warning when running this action
Screenshot 2022-10-22 at 09 56 49

### PR DESCRIPTION
**Pull request by erzz**
according to https://github.com/aws-actions/configure-aws-credentials/issues/540 it can perhaps resolve #112

### CODE REVIEW

**Comment by mr-smithers-excellent** [comment]
@erzz - nice! Thanks for the PR. I'm realizing I didn't leave the best (or any) contribution instructions in the `README`. 

You'll need to run `npm run build && git add dist/`, which I'm realizing I have set up in a [husky](https://github.com/typicode/husky) pre-commit hook.

**Comment by mr-smithers-excellent** [comment]
Looks like the warnings are still lingering, but we can get this merged anyhow and follow that open GH issue.

https://github.com/mr-smithers-excellent/docker-build-push/actions/runs/3338506646

**Comment by erzz** [comment]
Well we tried 🤷🏻

**Pull request merged**
