### PR TITLE
Ability to push multiple tags

### PR DESCRIPTION
**Pull request by asarazan**
This references issue https://github.com/mr-smithers-excellent/docker-build-push/issues/22

I went ahead and forked @belon's code and submitted a PR based on it. I'm happy to jump in and make changes as needed, though it may take me a minute. Let me know!

### CODE REVIEW

**Comment by belon** [comment]
Thanks @asarazan for help, I appreciate that. My apologies, I did not have time to do it.

**Comment by asarazan** [comment]
@belon no worries! Everybody benefits if this gets merged in, happy to help :-)

**Comment by mr-smithers-excellent** [comment]
Thanks @belon & @asarazan for the contribution! I'll cut a new release with this feature.

**Comment by jheckman-rt** [comment]
I use this in my pipeline and without having changed my code, my release tag is now now showing up and the build is failing.   It no longer creates the docker tag like it did previousy

NEW RESULTS
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props
Logging into ECR region us-east-2...
WARNING! Using -*** the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:

RESULTS FROM PREVIOUS BUILD:
Run mr-smithers-excellent/docker-build-push@master
  with:
    image: props
    registry: ***.dkr.ecr.us-east-2.amazonaws.com
    dockerfile: Dockerfile
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Creating Docker image tag...
Docker tag created: v3.2.0
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0
Logging into ECR region us-east-2...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0

**Pull request merged**
